export const INTELLIGENCE_TASKS = [
  "CASUAL_CHAT",
  "PLAYER_INTAKE",
  "PERSONAL_REFLECTION",
  "MEMORY_EXTRACTION",
  "ENTITY_EXTRACTION",
  "JOURNAL_CLASSIFICATION",
  "CONTENT_FORMATTING",
  "OPPORTUNITY_PREFILTER",
  "OPPORTUNITY_ANALYSIS",
  "OPPORTUNITY_RANKING",
  "SIDE_QUEST_GENERATION",
  "HIGH_IMPACT_SIDE_QUEST",
  "MAIN_QUEST_GENERATION",
  "CHAPTER_PLANNING",
  "TARGET_STATE_ANALYSIS",
  "CAMPAIGN_REVIEW",
  "CAMPAIGN_REPLAN",
  "STRATEGIC_DECISION",
  "NYX_EXPLANATION",
  "MISSION_COPY_GENERATION",
  "MONTHLY_WRAP_ANALYSIS",
  "PATTERN_DETECTION",
  "NYX_OUTREACH",
  "NYX_RELATIONSHIP_REVIEW",
] as const;

export type IntelligenceTask = (typeof INTELLIGENCE_TASKS)[number];

export function isIntelligenceTask(value: string): value is IntelligenceTask {
  return (INTELLIGENCE_TASKS as readonly string[]).includes(value);
}
