import type { StatKey } from "../src/server/domain/player/types";
import type {
  MissionDifficulty,
  MissionKind,
  MissionStatus,
  MissionTrack,
} from "../src/server/domain/mission/types";

export const SEED_CONTACTS = [
  { seedKey: "c-pieter", name: "Pieter Jan", role: "Ondernemer · productie", tier: "connector", lat: 51.0801, lng: 4.722, note: "Capaciteit is zijn bottleneck. Voorstel volgende week.", restricted: false },
  { seedKey: "c-rita", name: "Rita", role: "Ademcoach · klant", tier: "client", lat: 51.079, lng: 4.735, note: "Eerste klant. Zit nog op instaptarief.", restricted: false },
  { seedKey: "c-nico", name: "Nico", role: "Carbonherstelling", tier: "client", lat: 51.0512, lng: 4.6362, note: "Testimonial staat live.", restricted: false },
  { seedKey: "c-kevin", name: "Kevin", role: "13th Fool · maker", tier: "partner", lat: 51.1167, lng: 4.65, note: "Graphic design, 3D-print, merkbeleving.", restricted: false },
  { seedKey: "c-mike", name: "Mike", role: "Neef · bouw", tier: "warm", lat: 51.1667, lng: 4.6667, note: null, restricted: false },
  { seedKey: "c-christophe", name: "Christophe", role: "Warm netwerk", tier: "warm", lat: 51.1333, lng: 4.75, note: null, restricted: false },
  { seedKey: "c-anthony", name: "Anthony", role: "Warm netwerk", tier: "warm", lat: 50.9861, lng: 4.8361, note: null, restricted: false },
  { seedKey: "c-frans", name: "Frans", role: "Vader · clubs Nijlen–Herenthout–Berlaar", tier: "connector", lat: 51.156, lng: 4.664, note: "Bruggenbouwer naar de bredere Kempen.", restricted: false },
  { seedKey: "c-jdi", name: "JDI-relatie", role: "Restricted", tier: "restricted", lat: null, lng: null, note: "Concurrentiebeding. Nooit benaderen.", restricted: true },
];

type SeedObjective = { seedKey: string; label: string; optional?: boolean; done?: boolean };

export type SeedMission = {
  seedKey: string;
  kind: MissionKind;
  track: MissionTrack;
  title: string;
  why: string;
  mainObjective: string;
  status: MissionStatus;
  difficulty: MissionDifficulty;
  estimateLabel: string;
  impact: string;
  xpReward: number;
  xpGranted: number;
  statReward: { key: StatKey; amount: number };
  evidenceRequirement: string;
  locationName: string;
  locationAddress?: string;
  lat: number;
  lng: number;
  featured?: boolean;
  whenLabel?: string;
  people: string[];
  objectives: SeedObjective[];
};

export const SEED_MISSIONS: SeedMission[] = [
  {
    seedKey: "m-connector",
    kind: "MAIN",
    track: "MAIN_STORY",
    title: "THE CONNECTOR",
    why: "Uw netwerk heeft toegang nodig buiten uw huidige cirkel. Wie u vandaag kent, bepaalt welke kansen u volgend jaar te zien krijgt.",
    mainObjective: "Bouw 1 connector-relatie",
    status: "ACTIVE",
    difficulty: "MEDIUM",
    estimateLabel: "4 u over 14 dagen",
    impact: "Opent toegang tot 2 nieuwe netwerkkringen",
    xpReward: 250,
    xpGranted: 100,
    statReward: { key: "network", amount: 4 },
    evidenceRequirement: "Foto of notitie van de ontmoeting + naam van de connector in Journal",
    locationName: "Kempen — regiobreed",
    locationAddress: "Heist-op-den-Berg · Lier · Geel",
    lat: 51.0764,
    lng: 4.7283,
    featured: true,
    people: ["c-pieter", "c-mike", "c-christophe"],
    objectives: [
      { seedKey: "o1", label: "Identificeer 3 kandidaten", done: true },
      { seedKey: "o2", label: "Contacteer 2 kandidaten", done: true },
      { seedKey: "o3", label: "Ontmoet er 1 fysiek" },
      { seedKey: "o4", label: "Creëer waarde vóór je iets vraagt" },
      { seedKey: "o5", label: "Noteer wat hij nodig heeft", optional: true },
      { seedKey: "o6", label: "Follow-up binnen 48 uur", optional: true },
    ],
  },
  {
    seedKey: "m-voka",
    kind: "EVENT",
    track: "SIDE_QUEST",
    title: "VOKA EVENT — GEEL",
    why: "Drie potentiële partners in de technologiesector staan op de gastenlijst. Eén avond, drie deuren.",
    mainObjective: "Spreek 3 nieuwe mensen aan",
    status: "ACTIVE",
    difficulty: "LOW",
    estimateLabel: "3 u",
    impact: "Netwerk +3 en zicht op de technologiesector",
    xpReward: 250,
    xpGranted: 50,
    statReward: { key: "network", amount: 3 },
    evidenceRequirement: "Namen van 3 gesprekken in Journal",
    locationName: "Geel",
    locationAddress: "Lambertzlaan 10, Geel",
    lat: 51.1656,
    lng: 4.9906,
    whenLabel: "morgen · 19:00",
    people: ["c-christophe"],
    objectives: [
      { seedKey: "o1", label: "Gastenlijst scannen", done: true },
      { seedKey: "o2", label: "3 mensen aanspreken" },
      { seedKey: "o3", label: "1 concrete afspraak vastleggen" },
    ],
  },
  {
    seedKey: "m-q4",
    kind: "BUSINESS",
    track: "SIDE_QUEST",
    title: "Q4 STRATEGY REVIEW",
    why: "Zonder cijfers is groei een gevoel. Q4 bepaalt of hoofdstuk I sluit op schema.",
    mainObjective: "Targets en marges voor Q4 vastleggen",
    status: "ACTIVE",
    difficulty: "MEDIUM",
    estimateLabel: "2 u",
    impact: "Strategie +3 en scherper zicht op marge",
    xpReward: 100,
    xpGranted: 20,
    statReward: { key: "strategy", amount: 3 },
    evidenceRequirement: "Screenshot van het ingevulde overzicht",
    locationName: "Home Base",
    locationAddress: "Heist-op-den-Berg",
    lat: 51.0764,
    lng: 4.7283,
    people: [],
    objectives: [
      { seedKey: "o1", label: "Omzet en marge per klant uitrekenen", done: true },
      { seedKey: "o2", label: "Uurtarief herevalueren" },
      { seedKey: "o3", label: "Q4-doel vastleggen in één zin" },
    ],
  },
  {
    seedKey: "m-article",
    kind: "CONTENT",
    track: "SIDE_QUEST",
    title: "THOUGHT LEADERSHIP ARTICLE",
    why: "Autoriteit is het enige kanaal dat blijft werken terwijl u slaapt.",
    mainObjective: "Eén artikel publiceren over AI in het KMO-landschap",
    status: "ACTIVE",
    difficulty: "MEDIUM",
    estimateLabel: "3 u",
    impact: "Autoriteit +2, inbound aanvragen",
    xpReward: 75,
    xpGranted: 15,
    statReward: { key: "authority", amount: 2 },
    evidenceRequirement: "Link naar het gepubliceerde artikel",
    locationName: "Remote",
    lat: 51.0764,
    lng: 4.7283,
    people: [],
    objectives: [
      { seedKey: "o1", label: "Onderwerp en invalshoek kiezen", done: true },
      { seedKey: "o2", label: "Eerste versie schrijven" },
      { seedKey: "o3", label: "Publiceren en verspreiden" },
    ],
  },
  {
    seedKey: "m-lunch",
    kind: "NETWORK",
    track: "SIDE_QUEST",
    title: "LUNCH MET PIETER",
    why: "Capaciteit is zijn bottleneck. Dat is precies waar u waarde kunt leveren vóór u iets vraagt.",
    mainObjective: "Opvolggesprek inplannen en een voorstel voorbereiden",
    status: "PROPOSED",
    difficulty: "LOW",
    estimateLabel: "2 u",
    impact: "Netwerk +3 en een reële opdracht in beeld",
    xpReward: 120,
    xpGranted: 0,
    statReward: { key: "network", amount: 3 },
    evidenceRequirement: "Bevestigde afspraak in agenda",
    locationName: "Heist-op-den-Berg",
    lat: 51.0801,
    lng: 4.722,
    people: ["c-pieter"],
    objectives: [
      { seedKey: "o1", label: "Datum vastleggen" },
      { seedKey: "o2", label: "Voorstel op één pagina" },
    ],
  },
  {
    seedKey: "m-vastgoed",
    kind: "OPPORTUNITY",
    track: "SIDE_QUEST",
    title: "VERKEN VASTGOEDLOCATIE",
    why: "Optionality koopt u door vooraf te kijken, niet door te wachten tot u moet.",
    mainObjective: "Locatie ter plaatse beoordelen",
    status: "PROPOSED",
    difficulty: "LOW",
    estimateLabel: "1,5 u",
    impact: "Optionality +2",
    xpReward: 80,
    xpGranted: 0,
    statReward: { key: "optionality", amount: 2 },
    evidenceRequirement: "Foto + notitie",
    locationName: "Booischot",
    lat: 51.05,
    lng: 4.7833,
    people: [],
    objectives: [
      { seedKey: "o1", label: "Ligging en bereikbaarheid checken" },
      { seedKey: "o2", label: "Prijs per m² noteren" },
    ],
  },
  {
    seedKey: "m-boss10k",
    kind: "BOSS",
    track: "MAIN_STORY",
    title: "DE EERSTE €10K-MAAND",
    why: "Dit is de drempel waar de praktijk stopt met bijverdienste zijn. Alles daarvoor is voorbereiding.",
    mainObjective: "€10.000 omzet in één kalendermaand",
    status: "LOCKED",
    difficulty: "BOSS",
    estimateLabel: "1 kwartaal",
    impact: "Sluit hoofdstuk I. Capital +6, Income +5",
    xpReward: 1000,
    xpGranted: 0,
    statReward: { key: "capital", amount: 6 },
    evidenceRequirement: "Facturatie-overzicht van de maand",
    locationName: "Kempen",
    lat: 51.1,
    lng: 4.86,
    people: ["c-rita", "c-nico"],
    objectives: [
      { seedKey: "o1", label: "3 betalende klanten tegelijk" },
      { seedKey: "o2", label: "Tarief €180/u vasthouden" },
      { seedKey: "o3", label: "Eén klant op retainer" },
      { seedKey: "o4", label: "Twee weken buffer in de pijplijn" },
    ],
  },
  {
    seedKey: "m-unizo",
    kind: "EVENT",
    track: "SIDE_QUEST",
    title: "UNIZO NETWERKAVOND",
    why: "Lokale zichtbaarheid opbouwen in Heist.",
    mainObjective: "5 lokale ondernemers spreken",
    status: "COMPLETED",
    difficulty: "LOW",
    estimateLabel: "3 u",
    impact: "Netwerk +2",
    xpReward: 150,
    xpGranted: 150,
    statReward: { key: "network", amount: 2 },
    evidenceRequirement: "Namen in Journal",
    locationName: "Heist-op-den-Berg",
    lat: 51.0731,
    lng: 4.7305,
    people: [],
    objectives: [
      { seedKey: "o1", label: "Aanwezig zijn", done: true },
      { seedKey: "o2", label: "5 gesprekken", done: true },
    ],
  },
  {
    seedKey: "m-rita",
    kind: "BOSS",
    track: "MAIN_STORY",
    title: "EERSTE BETALENDE KLANT",
    why: "Bewijs dat het aanbod verkoopt zonder JDI achter uw naam.",
    mainObjective: "Eerste factuur versturen",
    status: "COMPLETED",
    difficulty: "BOSS",
    estimateLabel: "—",
    impact: "Capital +4, Income +3",
    xpReward: 600,
    xpGranted: 600,
    statReward: { key: "capital", amount: 4 },
    evidenceRequirement: "Betaalde factuur",
    locationName: "Heist-op-den-Berg",
    lat: 51.079,
    lng: 4.735,
    people: ["c-rita"],
    objectives: [
      { seedKey: "o1", label: "Aanbod scherpstellen", done: true },
      { seedKey: "o2", label: "Voorstel versturen", done: true },
      { seedKey: "o3", label: "Factureren", done: true },
    ],
  },
];
